// Code generated by swag init. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "tags": ["auth"],
                "summary": "Login user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {"type": "object"}
                }],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/auth/register": {
            "post": {
                "tags": ["auth"],
                "summary": "Register new user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/cart": {
            "get": {
                "tags": ["cart"],
                "summary": "Get cart",
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "tags": ["cart"],
                "summary": "Add item to cart",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/categories": {
            "get": {
                "tags": ["categories"],
                "summary": "Get all categories",
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/home": {
            "get": {
                "tags": ["home"],
                "summary": "Get home page data",
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/orders": {
            "post": {
                "tags": ["orders"],
                "summary": "Create order",
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/orders/my": {
            "get": {
                "tags": ["orders"],
                "summary": "Get user orders",
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/products": {
            "get": {
                "tags": ["products"],
                "summary": "Search and filter products",
                "produces": ["application/json"],
                "parameters": [
                    {"type": "string", "name": "q", "in": "query"},
                    {"type": "integer", "name": "category_id", "in": "query"},
                    {"type": "integer", "name": "store_id", "in": "query"},
                    {"type": "string", "name": "brand", "in": "query"},
                    {"type": "number", "name": "min_price", "in": "query"},
                    {"type": "number", "name": "max_price", "in": "query"},
                    {"type": "boolean", "name": "has_discount", "in": "query"},
                    {"type": "string", "name": "sort", "in": "query"}
                ],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/products/{id}": {
            "get": {
                "tags": ["products"],
                "summary": "Get product by ID",
                "produces": ["application/json"],
                "parameters": [{"type": "integer", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/stores": {
            "get": {
                "tags": ["stores"],
                "summary": "Get all stores",
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/users/me": {
            "get": {
                "tags": ["users"],
                "summary": "Get current user profile",
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "responses": {"200": {"description": "OK"}}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PriceCompare API",
	Description:      "API for comparing product prices across stores",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
